/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroIndexRouteImport } from './routes/cadastro.index'
import { Route as CadastroOrganizacaoRouteImport } from './routes/cadastro.organizacao'
import { Route as CadastroAdotanteRouteImport } from './routes/cadastro.adotante'
import { Route as CadastroAcolhedorRouteImport } from './routes/cadastro.acolhedor'
import { Route as AnimaisAnimalIdRouteImport } from './routes/animais.$animalId'
import { Route as AuthenticatedTriagemRouteImport } from './routes/_authenticated.triagem'
import { Route as AuthenticatedMinhasSolicitacoesRouteImport } from './routes/_authenticated.minhas-solicitacoes'
import { Route as AuthenticatedMeusFavoritosRouteImport } from './routes/_authenticated.meus-favoritos'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated.meu-perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardSolicitacoesRouteImport } from './routes/_authenticated.dashboard.solicitacoes'
import { Route as AuthenticatedDashboardPerfilRouteImport } from './routes/_authenticated.dashboard.perfil'
import { Route as AuthenticatedDashboardAnimaisRouteImport } from './routes/_authenticated.dashboard.animais'
import { Route as AuthenticatedDashboardAdotantesRouteImport } from './routes/_authenticated.dashboard.adotantes'
import { Route as AuthenticatedDashboardSolicitacoesIndexRouteImport } from './routes/_authenticated.dashboard.solicitacoes.index'
import { Route as AuthenticatedDashboardAnimaisIndexRouteImport } from './routes/_authenticated.dashboard.animais.index'
import { Route as AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport } from './routes/_authenticated.dashboard.solicitacoes.$solicitacaoId'
import { Route as AuthenticatedDashboardAnimaisNovoRouteImport } from './routes/_authenticated.dashboard.animais.novo'
import { Route as AuthenticatedDashboardAnimaisAnimalIdRouteImport } from './routes/_authenticated.dashboard.animais.$animalId'
import { Route as AuthenticatedDashboardAdminUsuariosRouteImport } from './routes/_authenticated.dashboard.admin.usuarios'

const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIndexRoute = CadastroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroOrganizacaoRoute = CadastroOrganizacaoRouteImport.update({
  id: '/organizacao',
  path: '/organizacao',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroAdotanteRoute = CadastroAdotanteRouteImport.update({
  id: '/adotante',
  path: '/adotante',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroAcolhedorRoute = CadastroAcolhedorRouteImport.update({
  id: '/acolhedor',
  path: '/acolhedor',
  getParentRoute: () => CadastroRoute,
} as any)
const AnimaisAnimalIdRoute = AnimaisAnimalIdRouteImport.update({
  id: '/animais/$animalId',
  path: '/animais/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTriagemRoute = AuthenticatedTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhasSolicitacoesRoute =
  AuthenticatedMinhasSolicitacoesRouteImport.update({
    id: '/minhas-solicitacoes',
    path: '/minhas-solicitacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeusFavoritosRoute =
  AuthenticatedMeusFavoritosRouteImport.update({
    id: '/meus-favoritos',
    path: '/meus-favoritos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesRoute =
  AuthenticatedDashboardSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerfilRoute =
  AuthenticatedDashboardPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnimaisRoute =
  AuthenticatedDashboardAnimaisRouteImport.update({
    id: '/animais',
    path: '/animais',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdotantesRoute =
  AuthenticatedDashboardAdotantesRouteImport.update({
    id: '/adotantes',
    path: '/adotantes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesIndexRoute =
  AuthenticatedDashboardSolicitacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSolicitacoesRoute,
  } as any)
const AuthenticatedDashboardAnimaisIndexRoute =
  AuthenticatedDashboardAnimaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute =
  AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport.update({
    id: '/$solicitacaoId',
    path: '/$solicitacaoId',
    getParentRoute: () => AuthenticatedDashboardSolicitacoesRoute,
  } as any)
const AuthenticatedDashboardAnimaisNovoRoute =
  AuthenticatedDashboardAnimaisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardAnimaisAnimalIdRoute =
  AuthenticatedDashboardAnimaisAnimalIdRouteImport.update({
    id: '/$animalId',
    path: '/$animalId',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardAdminUsuariosRoute =
  AuthenticatedDashboardAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/dashboard/adotantes': typeof AuthenticatedDashboardAdotantesRoute
  '/dashboard/animais': typeof AuthenticatedDashboardAnimaisRouteWithChildren
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/dashboard/animais/': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/dashboard/solicitacoes/': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/cadastro': typeof CadastroIndexRoute
  '/dashboard/adotantes': typeof AuthenticatedDashboardAdotantesRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/dashboard/animais': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/_authenticated/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/_authenticated/triagem': typeof AuthenticatedTriagemRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/_authenticated/dashboard/adotantes': typeof AuthenticatedDashboardAdotantesRoute
  '/_authenticated/dashboard/animais': typeof AuthenticatedDashboardAnimaisRouteWithChildren
  '/_authenticated/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/_authenticated/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/_authenticated/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/_authenticated/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/_authenticated/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/_authenticated/dashboard/animais/': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/_authenticated/dashboard/solicitacoes/': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/vitrine'
    | '/dashboard'
    | '/meu-perfil'
    | '/meus-favoritos'
    | '/minhas-solicitacoes'
    | '/triagem'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/cadastro/'
    | '/dashboard/adotantes'
    | '/dashboard/animais'
    | '/dashboard/perfil'
    | '/dashboard/solicitacoes'
    | '/dashboard/'
    | '/dashboard/admin/usuarios'
    | '/dashboard/animais/$animalId'
    | '/dashboard/animais/novo'
    | '/dashboard/solicitacoes/$solicitacaoId'
    | '/dashboard/animais/'
    | '/dashboard/solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vitrine'
    | '/meu-perfil'
    | '/meus-favoritos'
    | '/minhas-solicitacoes'
    | '/triagem'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/cadastro'
    | '/dashboard/adotantes'
    | '/dashboard/perfil'
    | '/dashboard'
    | '/dashboard/admin/usuarios'
    | '/dashboard/animais/$animalId'
    | '/dashboard/animais/novo'
    | '/dashboard/solicitacoes/$solicitacaoId'
    | '/dashboard/animais'
    | '/dashboard/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/vitrine'
    | '/_authenticated/dashboard'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/meus-favoritos'
    | '/_authenticated/minhas-solicitacoes'
    | '/_authenticated/triagem'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/cadastro/'
    | '/_authenticated/dashboard/adotantes'
    | '/_authenticated/dashboard/animais'
    | '/_authenticated/dashboard/perfil'
    | '/_authenticated/dashboard/solicitacoes'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/usuarios'
    | '/_authenticated/dashboard/animais/$animalId'
    | '/_authenticated/dashboard/animais/novo'
    | '/_authenticated/dashboard/solicitacoes/$solicitacaoId'
    | '/_authenticated/dashboard/animais/'
    | '/_authenticated/dashboard/solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRouteWithChildren
  LoginRoute: typeof LoginRoute
  VitrineRoute: typeof VitrineRoute
  AnimaisAnimalIdRoute: typeof AnimaisAnimalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/': {
      id: '/cadastro/'
      path: '/'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof CadastroIndexRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/organizacao': {
      id: '/cadastro/organizacao'
      path: '/organizacao'
      fullPath: '/cadastro/organizacao'
      preLoaderRoute: typeof CadastroOrganizacaoRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/adotante': {
      id: '/cadastro/adotante'
      path: '/adotante'
      fullPath: '/cadastro/adotante'
      preLoaderRoute: typeof CadastroAdotanteRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/acolhedor': {
      id: '/cadastro/acolhedor'
      path: '/acolhedor'
      fullPath: '/cadastro/acolhedor'
      preLoaderRoute: typeof CadastroAcolhedorRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/animais/$animalId': {
      id: '/animais/$animalId'
      path: '/animais/$animalId'
      fullPath: '/animais/$animalId'
      preLoaderRoute: typeof AnimaisAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/triagem': {
      id: '/_authenticated/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AuthenticatedTriagemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-solicitacoes': {
      id: '/_authenticated/minhas-solicitacoes'
      path: '/minhas-solicitacoes'
      fullPath: '/minhas-solicitacoes'
      preLoaderRoute: typeof AuthenticatedMinhasSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meus-favoritos': {
      id: '/_authenticated/meus-favoritos'
      path: '/meus-favoritos'
      fullPath: '/meus-favoritos'
      preLoaderRoute: typeof AuthenticatedMeusFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/solicitacoes': {
      id: '/_authenticated/dashboard/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/dashboard/solicitacoes'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/perfil': {
      id: '/_authenticated/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof AuthenticatedDashboardPerfilRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/animais': {
      id: '/_authenticated/dashboard/animais'
      path: '/animais'
      fullPath: '/dashboard/animais'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/adotantes': {
      id: '/_authenticated/dashboard/adotantes'
      path: '/adotantes'
      fullPath: '/dashboard/adotantes'
      preLoaderRoute: typeof AuthenticatedDashboardAdotantesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/solicitacoes/': {
      id: '/_authenticated/dashboard/solicitacoes/'
      path: '/'
      fullPath: '/dashboard/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSolicitacoesRoute
    }
    '/_authenticated/dashboard/animais/': {
      id: '/_authenticated/dashboard/animais/'
      path: '/'
      fullPath: '/dashboard/animais/'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/solicitacoes/$solicitacaoId': {
      id: '/_authenticated/dashboard/solicitacoes/$solicitacaoId'
      path: '/$solicitacaoId'
      fullPath: '/dashboard/solicitacoes/$solicitacaoId'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSolicitacoesRoute
    }
    '/_authenticated/dashboard/animais/novo': {
      id: '/_authenticated/dashboard/animais/novo'
      path: '/novo'
      fullPath: '/dashboard/animais/novo'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisNovoRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/animais/$animalId': {
      id: '/_authenticated/dashboard/animais/$animalId'
      path: '/$animalId'
      fullPath: '/dashboard/animais/$animalId'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisAnimalIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/admin/usuarios': {
      id: '/_authenticated/dashboard/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/dashboard/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardAnimaisRouteChildren {
  AuthenticatedDashboardAnimaisAnimalIdRoute: typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  AuthenticatedDashboardAnimaisNovoRoute: typeof AuthenticatedDashboardAnimaisNovoRoute
  AuthenticatedDashboardAnimaisIndexRoute: typeof AuthenticatedDashboardAnimaisIndexRoute
}

const AuthenticatedDashboardAnimaisRouteChildren: AuthenticatedDashboardAnimaisRouteChildren =
  {
    AuthenticatedDashboardAnimaisAnimalIdRoute:
      AuthenticatedDashboardAnimaisAnimalIdRoute,
    AuthenticatedDashboardAnimaisNovoRoute:
      AuthenticatedDashboardAnimaisNovoRoute,
    AuthenticatedDashboardAnimaisIndexRoute:
      AuthenticatedDashboardAnimaisIndexRoute,
  }

const AuthenticatedDashboardAnimaisRouteWithChildren =
  AuthenticatedDashboardAnimaisRoute._addFileChildren(
    AuthenticatedDashboardAnimaisRouteChildren,
  )

interface AuthenticatedDashboardSolicitacoesRouteChildren {
  AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute: typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  AuthenticatedDashboardSolicitacoesIndexRoute: typeof AuthenticatedDashboardSolicitacoesIndexRoute
}

const AuthenticatedDashboardSolicitacoesRouteChildren: AuthenticatedDashboardSolicitacoesRouteChildren =
  {
    AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute:
      AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute,
    AuthenticatedDashboardSolicitacoesIndexRoute:
      AuthenticatedDashboardSolicitacoesIndexRoute,
  }

const AuthenticatedDashboardSolicitacoesRouteWithChildren =
  AuthenticatedDashboardSolicitacoesRoute._addFileChildren(
    AuthenticatedDashboardSolicitacoesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdotantesRoute: typeof AuthenticatedDashboardAdotantesRoute
  AuthenticatedDashboardAnimaisRoute: typeof AuthenticatedDashboardAnimaisRouteWithChildren
  AuthenticatedDashboardPerfilRoute: typeof AuthenticatedDashboardPerfilRoute
  AuthenticatedDashboardSolicitacoesRoute: typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminUsuariosRoute: typeof AuthenticatedDashboardAdminUsuariosRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdotantesRoute: AuthenticatedDashboardAdotantesRoute,
    AuthenticatedDashboardAnimaisRoute:
      AuthenticatedDashboardAnimaisRouteWithChildren,
    AuthenticatedDashboardPerfilRoute: AuthenticatedDashboardPerfilRoute,
    AuthenticatedDashboardSolicitacoesRoute:
      AuthenticatedDashboardSolicitacoesRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminUsuariosRoute:
      AuthenticatedDashboardAdminUsuariosRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedMeusFavoritosRoute: typeof AuthenticatedMeusFavoritosRoute
  AuthenticatedMinhasSolicitacoesRoute: typeof AuthenticatedMinhasSolicitacoesRoute
  AuthenticatedTriagemRoute: typeof AuthenticatedTriagemRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedMeusFavoritosRoute: AuthenticatedMeusFavoritosRoute,
  AuthenticatedMinhasSolicitacoesRoute: AuthenticatedMinhasSolicitacoesRoute,
  AuthenticatedTriagemRoute: AuthenticatedTriagemRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CadastroRouteChildren {
  CadastroAcolhedorRoute: typeof CadastroAcolhedorRoute
  CadastroAdotanteRoute: typeof CadastroAdotanteRoute
  CadastroOrganizacaoRoute: typeof CadastroOrganizacaoRoute
  CadastroIndexRoute: typeof CadastroIndexRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroAcolhedorRoute: CadastroAcolhedorRoute,
  CadastroAdotanteRoute: CadastroAdotanteRoute,
  CadastroOrganizacaoRoute: CadastroOrganizacaoRoute,
  CadastroIndexRoute: CadastroIndexRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRouteWithChildren,
  LoginRoute: LoginRoute,
  VitrineRoute: VitrineRoute,
  AnimaisAnimalIdRoute: AnimaisAnimalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
