/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedFeelsRouteImport } from './routes/_authenticated.feels'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated.mensagens'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated.meu-perfil'
import { Route as AuthenticatedMeusFavoritosRouteImport } from './routes/_authenticated.meus-favoritos'
import { Route as AuthenticatedMinhasSolicitacoesRouteImport } from './routes/_authenticated.minhas-solicitacoes'
import { Route as AuthenticatedTriagemRouteImport } from './routes/_authenticated.triagem'
import { Route as AdotantesAdotanteIdRouteImport } from './routes/adotantes.$adotanteId'
import { Route as AnimaisAnimalIdRouteImport } from './routes/animais.$animalId'
import { Route as CadastroIndexRouteImport } from './routes/cadastro.index'
import { Route as CadastroAcolhedorRouteImport } from './routes/cadastro.acolhedor'
import { Route as CadastroAdotanteRouteImport } from './routes/cadastro.adotante'
import { Route as CadastroOrganizacaoRouteImport } from './routes/cadastro.organizacao'
import { Route as OrganizacoesOrganizacaoIdRouteImport } from './routes/organizacoes.$organizacaoId'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardAdotadosRouteImport } from './routes/_authenticated.dashboard.adotados'
import { Route as AuthenticatedDashboardAnimaisRouteImport } from './routes/_authenticated.dashboard.animais'
import { Route as AuthenticatedDashboardDocumentosRouteImport } from './routes/_authenticated.dashboard.documentos'
import { Route as AuthenticatedDashboardMensagensRouteImport } from './routes/_authenticated.dashboard.mensagens'
import { Route as AuthenticatedDashboardPerfilRouteImport } from './routes/_authenticated.dashboard.perfil'
import { Route as AuthenticatedDashboardSaudeRouteImport } from './routes/_authenticated.dashboard.saude'
import { Route as AuthenticatedDashboardSolicitacoesRouteImport } from './routes/_authenticated.dashboard.solicitacoes'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated.mensagens.index'
import { Route as AuthenticatedMensagensConversaIdRouteImport } from './routes/_authenticated.mensagens.$conversaId'
import { Route as AuthenticatedDashboardAdminUsuariosRouteImport } from './routes/_authenticated.dashboard.admin.usuarios'
import { Route as AuthenticatedDashboardAnimaisIndexRouteImport } from './routes/_authenticated.dashboard.animais.index'
import { Route as AuthenticatedDashboardAnimaisAnimalIdRouteImport } from './routes/_authenticated.dashboard.animais.$animalId'
import { Route as AuthenticatedDashboardAnimaisNovoRouteImport } from './routes/_authenticated.dashboard.animais.novo'
import { Route as AuthenticatedDashboardDocumentosIndexRouteImport } from './routes/_authenticated.dashboard.documentos.index'
import { Route as AuthenticatedDashboardMensagensIndexRouteImport } from './routes/_authenticated.dashboard.mensagens.index'
import { Route as AuthenticatedDashboardMensagensConversaIdRouteImport } from './routes/_authenticated.dashboard.mensagens.$conversaId'
import { Route as AuthenticatedDashboardSaudeIndexRouteImport } from './routes/_authenticated.dashboard.saude.index'
import { Route as AuthenticatedDashboardSolicitacoesIndexRouteImport } from './routes/_authenticated.dashboard.solicitacoes.index'
import { Route as AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport } from './routes/_authenticated.dashboard.solicitacoes.$solicitacaoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeelsRoute = AuthenticatedFeelsRouteImport.update({
  id: '/feels',
  path: '/feels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeusFavoritosRoute =
  AuthenticatedMeusFavoritosRouteImport.update({
    id: '/meus-favoritos',
    path: '/meus-favoritos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhasSolicitacoesRoute =
  AuthenticatedMinhasSolicitacoesRouteImport.update({
    id: '/minhas-solicitacoes',
    path: '/minhas-solicitacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTriagemRoute = AuthenticatedTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdotantesAdotanteIdRoute = AdotantesAdotanteIdRouteImport.update({
  id: '/adotantes/$adotanteId',
  path: '/adotantes/$adotanteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdRoute = AnimaisAnimalIdRouteImport.update({
  id: '/animais/$animalId',
  path: '/animais/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIndexRoute = CadastroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroAcolhedorRoute = CadastroAcolhedorRouteImport.update({
  id: '/acolhedor',
  path: '/acolhedor',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroAdotanteRoute = CadastroAdotanteRouteImport.update({
  id: '/adotante',
  path: '/adotante',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroOrganizacaoRoute = CadastroOrganizacaoRouteImport.update({
  id: '/organizacao',
  path: '/organizacao',
  getParentRoute: () => CadastroRoute,
} as any)
const OrganizacoesOrganizacaoIdRoute =
  OrganizacoesOrganizacaoIdRouteImport.update({
    id: '/organizacoes/$organizacaoId',
    path: '/organizacoes/$organizacaoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdotadosRoute =
  AuthenticatedDashboardAdotadosRouteImport.update({
    id: '/adotados',
    path: '/adotados',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnimaisRoute =
  AuthenticatedDashboardAnimaisRouteImport.update({
    id: '/animais',
    path: '/animais',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentosRoute =
  AuthenticatedDashboardDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMensagensRoute =
  AuthenticatedDashboardMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerfilRoute =
  AuthenticatedDashboardPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSaudeRoute =
  AuthenticatedDashboardSaudeRouteImport.update({
    id: '/saude',
    path: '/saude',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesRoute =
  AuthenticatedDashboardSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMensagensRoute,
  } as any)
const AuthenticatedMensagensConversaIdRoute =
  AuthenticatedMensagensConversaIdRouteImport.update({
    id: '/$conversaId',
    path: '/$conversaId',
    getParentRoute: () => AuthenticatedMensagensRoute,
  } as any)
const AuthenticatedDashboardAdminUsuariosRoute =
  AuthenticatedDashboardAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnimaisIndexRoute =
  AuthenticatedDashboardAnimaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardAnimaisAnimalIdRoute =
  AuthenticatedDashboardAnimaisAnimalIdRouteImport.update({
    id: '/$animalId',
    path: '/$animalId',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardAnimaisNovoRoute =
  AuthenticatedDashboardAnimaisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedDashboardAnimaisRoute,
  } as any)
const AuthenticatedDashboardDocumentosIndexRoute =
  AuthenticatedDashboardDocumentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDocumentosRoute,
  } as any)
const AuthenticatedDashboardMensagensIndexRoute =
  AuthenticatedDashboardMensagensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardMensagensRoute,
  } as any)
const AuthenticatedDashboardMensagensConversaIdRoute =
  AuthenticatedDashboardMensagensConversaIdRouteImport.update({
    id: '/$conversaId',
    path: '/$conversaId',
    getParentRoute: () => AuthenticatedDashboardMensagensRoute,
  } as any)
const AuthenticatedDashboardSaudeIndexRoute =
  AuthenticatedDashboardSaudeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSaudeRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesIndexRoute =
  AuthenticatedDashboardSolicitacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSolicitacoesRoute,
  } as any)
const AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute =
  AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport.update({
    id: '/$solicitacaoId',
    path: '/$solicitacaoId',
    getParentRoute: () => AuthenticatedDashboardSolicitacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/feels': typeof AuthenticatedFeelsRoute
  '/mensagens': typeof AuthenticatedMensagensRouteWithChildren
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/adotantes/$adotanteId': typeof AdotantesAdotanteIdRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/organizacoes/$organizacaoId': typeof OrganizacoesOrganizacaoIdRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/dashboard/adotados': typeof AuthenticatedDashboardAdotadosRoute
  '/dashboard/animais': typeof AuthenticatedDashboardAnimaisRouteWithChildren
  '/dashboard/documentos': typeof AuthenticatedDashboardDocumentosRouteWithChildren
  '/dashboard/mensagens': typeof AuthenticatedDashboardMensagensRouteWithChildren
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/dashboard/saude': typeof AuthenticatedDashboardSaudeRouteWithChildren
  '/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/dashboard/mensagens/$conversaId': typeof AuthenticatedDashboardMensagensConversaIdRoute
  '/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/dashboard/animais/': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/dashboard/documentos/': typeof AuthenticatedDashboardDocumentosIndexRoute
  '/dashboard/mensagens/': typeof AuthenticatedDashboardMensagensIndexRoute
  '/dashboard/saude/': typeof AuthenticatedDashboardSaudeIndexRoute
  '/dashboard/solicitacoes/': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/feels': typeof AuthenticatedFeelsRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/triagem': typeof AuthenticatedTriagemRoute
  '/adotantes/$adotanteId': typeof AdotantesAdotanteIdRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/organizacoes/$organizacaoId': typeof OrganizacoesOrganizacaoIdRoute
  '/cadastro': typeof CadastroIndexRoute
  '/dashboard/adotados': typeof AuthenticatedDashboardAdotadosRoute
  '/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/dashboard/mensagens/$conversaId': typeof AuthenticatedDashboardMensagensConversaIdRoute
  '/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/dashboard/animais': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/dashboard/documentos': typeof AuthenticatedDashboardDocumentosIndexRoute
  '/dashboard/mensagens': typeof AuthenticatedDashboardMensagensIndexRoute
  '/dashboard/saude': typeof AuthenticatedDashboardSaudeIndexRoute
  '/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/vitrine': typeof VitrineRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/feels': typeof AuthenticatedFeelsRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRouteWithChildren
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/meus-favoritos': typeof AuthenticatedMeusFavoritosRoute
  '/_authenticated/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/_authenticated/triagem': typeof AuthenticatedTriagemRoute
  '/adotantes/$adotanteId': typeof AdotantesAdotanteIdRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/cadastro/acolhedor': typeof CadastroAcolhedorRoute
  '/cadastro/adotante': typeof CadastroAdotanteRoute
  '/cadastro/organizacao': typeof CadastroOrganizacaoRoute
  '/organizacoes/$organizacaoId': typeof OrganizacoesOrganizacaoIdRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/_authenticated/dashboard/adotados': typeof AuthenticatedDashboardAdotadosRoute
  '/_authenticated/dashboard/animais': typeof AuthenticatedDashboardAnimaisRouteWithChildren
  '/_authenticated/dashboard/documentos': typeof AuthenticatedDashboardDocumentosRouteWithChildren
  '/_authenticated/dashboard/mensagens': typeof AuthenticatedDashboardMensagensRouteWithChildren
  '/_authenticated/dashboard/perfil': typeof AuthenticatedDashboardPerfilRoute
  '/_authenticated/dashboard/saude': typeof AuthenticatedDashboardSaudeRouteWithChildren
  '/_authenticated/dashboard/solicitacoes': typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  '/_authenticated/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/dashboard/admin/usuarios': typeof AuthenticatedDashboardAdminUsuariosRoute
  '/_authenticated/dashboard/animais/$animalId': typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  '/_authenticated/dashboard/animais/novo': typeof AuthenticatedDashboardAnimaisNovoRoute
  '/_authenticated/dashboard/mensagens/$conversaId': typeof AuthenticatedDashboardMensagensConversaIdRoute
  '/_authenticated/dashboard/solicitacoes/$solicitacaoId': typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  '/_authenticated/dashboard/animais/': typeof AuthenticatedDashboardAnimaisIndexRoute
  '/_authenticated/dashboard/documentos/': typeof AuthenticatedDashboardDocumentosIndexRoute
  '/_authenticated/dashboard/mensagens/': typeof AuthenticatedDashboardMensagensIndexRoute
  '/_authenticated/dashboard/saude/': typeof AuthenticatedDashboardSaudeIndexRoute
  '/_authenticated/dashboard/solicitacoes/': typeof AuthenticatedDashboardSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/cadastro'
    | '/login'
    | '/vitrine'
    | '/dashboard'
    | '/feels'
    | '/mensagens'
    | '/meu-perfil'
    | '/meus-favoritos'
    | '/minhas-solicitacoes'
    | '/triagem'
    | '/adotantes/$adotanteId'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/organizacoes/$organizacaoId'
    | '/cadastro/'
    | '/dashboard/adotados'
    | '/dashboard/animais'
    | '/dashboard/documentos'
    | '/dashboard/mensagens'
    | '/dashboard/perfil'
    | '/dashboard/saude'
    | '/dashboard/solicitacoes'
    | '/mensagens/$conversaId'
    | '/dashboard/'
    | '/mensagens/'
    | '/dashboard/admin/usuarios'
    | '/dashboard/animais/$animalId'
    | '/dashboard/animais/novo'
    | '/dashboard/mensagens/$conversaId'
    | '/dashboard/solicitacoes/$solicitacaoId'
    | '/dashboard/animais/'
    | '/dashboard/documentos/'
    | '/dashboard/mensagens/'
    | '/dashboard/saude/'
    | '/dashboard/solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/login'
    | '/vitrine'
    | '/feels'
    | '/meu-perfil'
    | '/meus-favoritos'
    | '/minhas-solicitacoes'
    | '/triagem'
    | '/adotantes/$adotanteId'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/organizacoes/$organizacaoId'
    | '/cadastro'
    | '/dashboard/adotados'
    | '/dashboard/perfil'
    | '/mensagens/$conversaId'
    | '/dashboard'
    | '/mensagens'
    | '/dashboard/admin/usuarios'
    | '/dashboard/animais/$animalId'
    | '/dashboard/animais/novo'
    | '/dashboard/mensagens/$conversaId'
    | '/dashboard/solicitacoes/$solicitacaoId'
    | '/dashboard/animais'
    | '/dashboard/documentos'
    | '/dashboard/mensagens'
    | '/dashboard/saude'
    | '/dashboard/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/busca'
    | '/cadastro'
    | '/login'
    | '/vitrine'
    | '/_authenticated/dashboard'
    | '/_authenticated/feels'
    | '/_authenticated/mensagens'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/meus-favoritos'
    | '/_authenticated/minhas-solicitacoes'
    | '/_authenticated/triagem'
    | '/adotantes/$adotanteId'
    | '/animais/$animalId'
    | '/cadastro/acolhedor'
    | '/cadastro/adotante'
    | '/cadastro/organizacao'
    | '/organizacoes/$organizacaoId'
    | '/cadastro/'
    | '/_authenticated/dashboard/adotados'
    | '/_authenticated/dashboard/animais'
    | '/_authenticated/dashboard/documentos'
    | '/_authenticated/dashboard/mensagens'
    | '/_authenticated/dashboard/perfil'
    | '/_authenticated/dashboard/saude'
    | '/_authenticated/dashboard/solicitacoes'
    | '/_authenticated/mensagens/$conversaId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/mensagens/'
    | '/_authenticated/dashboard/admin/usuarios'
    | '/_authenticated/dashboard/animais/$animalId'
    | '/_authenticated/dashboard/animais/novo'
    | '/_authenticated/dashboard/mensagens/$conversaId'
    | '/_authenticated/dashboard/solicitacoes/$solicitacaoId'
    | '/_authenticated/dashboard/animais/'
    | '/_authenticated/dashboard/documentos/'
    | '/_authenticated/dashboard/mensagens/'
    | '/_authenticated/dashboard/saude/'
    | '/_authenticated/dashboard/solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CadastroRoute: typeof CadastroRouteWithChildren
  LoginRoute: typeof LoginRoute
  VitrineRoute: typeof VitrineRoute
  AdotantesAdotanteIdRoute: typeof AdotantesAdotanteIdRoute
  AnimaisAnimalIdRoute: typeof AnimaisAnimalIdRoute
  OrganizacoesOrganizacaoIdRoute: typeof OrganizacoesOrganizacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feels': {
      id: '/_authenticated/feels'
      path: '/feels'
      fullPath: '/feels'
      preLoaderRoute: typeof AuthenticatedFeelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meus-favoritos': {
      id: '/_authenticated/meus-favoritos'
      path: '/meus-favoritos'
      fullPath: '/meus-favoritos'
      preLoaderRoute: typeof AuthenticatedMeusFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-solicitacoes': {
      id: '/_authenticated/minhas-solicitacoes'
      path: '/minhas-solicitacoes'
      fullPath: '/minhas-solicitacoes'
      preLoaderRoute: typeof AuthenticatedMinhasSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/triagem': {
      id: '/_authenticated/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof AuthenticatedTriagemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/adotantes/$adotanteId': {
      id: '/adotantes/$adotanteId'
      path: '/adotantes/$adotanteId'
      fullPath: '/adotantes/$adotanteId'
      preLoaderRoute: typeof AdotantesAdotanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId': {
      id: '/animais/$animalId'
      path: '/animais/$animalId'
      fullPath: '/animais/$animalId'
      preLoaderRoute: typeof AnimaisAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/': {
      id: '/cadastro/'
      path: '/'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof CadastroIndexRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/acolhedor': {
      id: '/cadastro/acolhedor'
      path: '/acolhedor'
      fullPath: '/cadastro/acolhedor'
      preLoaderRoute: typeof CadastroAcolhedorRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/adotante': {
      id: '/cadastro/adotante'
      path: '/adotante'
      fullPath: '/cadastro/adotante'
      preLoaderRoute: typeof CadastroAdotanteRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/organizacao': {
      id: '/cadastro/organizacao'
      path: '/organizacao'
      fullPath: '/cadastro/organizacao'
      preLoaderRoute: typeof CadastroOrganizacaoRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/organizacoes/$organizacaoId': {
      id: '/organizacoes/$organizacaoId'
      path: '/organizacoes/$organizacaoId'
      fullPath: '/organizacoes/$organizacaoId'
      preLoaderRoute: typeof OrganizacoesOrganizacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/adotados': {
      id: '/_authenticated/dashboard/adotados'
      path: '/adotados'
      fullPath: '/dashboard/adotados'
      preLoaderRoute: typeof AuthenticatedDashboardAdotadosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/animais': {
      id: '/_authenticated/dashboard/animais'
      path: '/animais'
      fullPath: '/dashboard/animais'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documentos': {
      id: '/_authenticated/dashboard/documentos'
      path: '/documentos'
      fullPath: '/dashboard/documentos'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mensagens': {
      id: '/_authenticated/dashboard/mensagens'
      path: '/mensagens'
      fullPath: '/dashboard/mensagens'
      preLoaderRoute: typeof AuthenticatedDashboardMensagensRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/perfil': {
      id: '/_authenticated/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof AuthenticatedDashboardPerfilRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/saude': {
      id: '/_authenticated/dashboard/saude'
      path: '/saude'
      fullPath: '/dashboard/saude'
      preLoaderRoute: typeof AuthenticatedDashboardSaudeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/solicitacoes': {
      id: '/_authenticated/dashboard/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/dashboard/solicitacoes'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedMensagensRoute
    }
    '/_authenticated/mensagens/$conversaId': {
      id: '/_authenticated/mensagens/$conversaId'
      path: '/$conversaId'
      fullPath: '/mensagens/$conversaId'
      preLoaderRoute: typeof AuthenticatedMensagensConversaIdRouteImport
      parentRoute: typeof AuthenticatedMensagensRoute
    }
    '/_authenticated/dashboard/admin/usuarios': {
      id: '/_authenticated/dashboard/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/dashboard/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/animais/': {
      id: '/_authenticated/dashboard/animais/'
      path: '/'
      fullPath: '/dashboard/animais/'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/animais/$animalId': {
      id: '/_authenticated/dashboard/animais/$animalId'
      path: '/$animalId'
      fullPath: '/dashboard/animais/$animalId'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisAnimalIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/animais/novo': {
      id: '/_authenticated/dashboard/animais/novo'
      path: '/novo'
      fullPath: '/dashboard/animais/novo'
      preLoaderRoute: typeof AuthenticatedDashboardAnimaisNovoRouteImport
      parentRoute: typeof AuthenticatedDashboardAnimaisRoute
    }
    '/_authenticated/dashboard/documentos/': {
      id: '/_authenticated/dashboard/documentos/'
      path: '/'
      fullPath: '/dashboard/documentos/'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDocumentosRoute
    }
    '/_authenticated/dashboard/mensagens/': {
      id: '/_authenticated/dashboard/mensagens/'
      path: '/'
      fullPath: '/dashboard/mensagens/'
      preLoaderRoute: typeof AuthenticatedDashboardMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardMensagensRoute
    }
    '/_authenticated/dashboard/mensagens/$conversaId': {
      id: '/_authenticated/dashboard/mensagens/$conversaId'
      path: '/$conversaId'
      fullPath: '/dashboard/mensagens/$conversaId'
      preLoaderRoute: typeof AuthenticatedDashboardMensagensConversaIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMensagensRoute
    }
    '/_authenticated/dashboard/saude/': {
      id: '/_authenticated/dashboard/saude/'
      path: '/'
      fullPath: '/dashboard/saude/'
      preLoaderRoute: typeof AuthenticatedDashboardSaudeIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSaudeRoute
    }
    '/_authenticated/dashboard/solicitacoes/': {
      id: '/_authenticated/dashboard/solicitacoes/'
      path: '/'
      fullPath: '/dashboard/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSolicitacoesRoute
    }
    '/_authenticated/dashboard/solicitacoes/$solicitacaoId': {
      id: '/_authenticated/dashboard/solicitacoes/$solicitacaoId'
      path: '/$solicitacaoId'
      fullPath: '/dashboard/solicitacoes/$solicitacaoId'
      preLoaderRoute: typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSolicitacoesRoute
    }
  }
}

interface AuthenticatedDashboardAnimaisRouteChildren {
  AuthenticatedDashboardAnimaisAnimalIdRoute: typeof AuthenticatedDashboardAnimaisAnimalIdRoute
  AuthenticatedDashboardAnimaisNovoRoute: typeof AuthenticatedDashboardAnimaisNovoRoute
  AuthenticatedDashboardAnimaisIndexRoute: typeof AuthenticatedDashboardAnimaisIndexRoute
}

const AuthenticatedDashboardAnimaisRouteChildren: AuthenticatedDashboardAnimaisRouteChildren =
  {
    AuthenticatedDashboardAnimaisAnimalIdRoute:
      AuthenticatedDashboardAnimaisAnimalIdRoute,
    AuthenticatedDashboardAnimaisNovoRoute:
      AuthenticatedDashboardAnimaisNovoRoute,
    AuthenticatedDashboardAnimaisIndexRoute:
      AuthenticatedDashboardAnimaisIndexRoute,
  }

const AuthenticatedDashboardAnimaisRouteWithChildren =
  AuthenticatedDashboardAnimaisRoute._addFileChildren(
    AuthenticatedDashboardAnimaisRouteChildren,
  )

interface AuthenticatedDashboardDocumentosRouteChildren {
  AuthenticatedDashboardDocumentosIndexRoute: typeof AuthenticatedDashboardDocumentosIndexRoute
}

const AuthenticatedDashboardDocumentosRouteChildren: AuthenticatedDashboardDocumentosRouteChildren =
  {
    AuthenticatedDashboardDocumentosIndexRoute:
      AuthenticatedDashboardDocumentosIndexRoute,
  }

const AuthenticatedDashboardDocumentosRouteWithChildren =
  AuthenticatedDashboardDocumentosRoute._addFileChildren(
    AuthenticatedDashboardDocumentosRouteChildren,
  )

interface AuthenticatedDashboardMensagensRouteChildren {
  AuthenticatedDashboardMensagensConversaIdRoute: typeof AuthenticatedDashboardMensagensConversaIdRoute
  AuthenticatedDashboardMensagensIndexRoute: typeof AuthenticatedDashboardMensagensIndexRoute
}

const AuthenticatedDashboardMensagensRouteChildren: AuthenticatedDashboardMensagensRouteChildren =
  {
    AuthenticatedDashboardMensagensConversaIdRoute:
      AuthenticatedDashboardMensagensConversaIdRoute,
    AuthenticatedDashboardMensagensIndexRoute:
      AuthenticatedDashboardMensagensIndexRoute,
  }

const AuthenticatedDashboardMensagensRouteWithChildren =
  AuthenticatedDashboardMensagensRoute._addFileChildren(
    AuthenticatedDashboardMensagensRouteChildren,
  )

interface AuthenticatedDashboardSaudeRouteChildren {
  AuthenticatedDashboardSaudeIndexRoute: typeof AuthenticatedDashboardSaudeIndexRoute
}

const AuthenticatedDashboardSaudeRouteChildren: AuthenticatedDashboardSaudeRouteChildren =
  {
    AuthenticatedDashboardSaudeIndexRoute:
      AuthenticatedDashboardSaudeIndexRoute,
  }

const AuthenticatedDashboardSaudeRouteWithChildren =
  AuthenticatedDashboardSaudeRoute._addFileChildren(
    AuthenticatedDashboardSaudeRouteChildren,
  )

interface AuthenticatedDashboardSolicitacoesRouteChildren {
  AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute: typeof AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute
  AuthenticatedDashboardSolicitacoesIndexRoute: typeof AuthenticatedDashboardSolicitacoesIndexRoute
}

const AuthenticatedDashboardSolicitacoesRouteChildren: AuthenticatedDashboardSolicitacoesRouteChildren =
  {
    AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute:
      AuthenticatedDashboardSolicitacoesSolicitacaoIdRoute,
    AuthenticatedDashboardSolicitacoesIndexRoute:
      AuthenticatedDashboardSolicitacoesIndexRoute,
  }

const AuthenticatedDashboardSolicitacoesRouteWithChildren =
  AuthenticatedDashboardSolicitacoesRoute._addFileChildren(
    AuthenticatedDashboardSolicitacoesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdotadosRoute: typeof AuthenticatedDashboardAdotadosRoute
  AuthenticatedDashboardAnimaisRoute: typeof AuthenticatedDashboardAnimaisRouteWithChildren
  AuthenticatedDashboardDocumentosRoute: typeof AuthenticatedDashboardDocumentosRouteWithChildren
  AuthenticatedDashboardMensagensRoute: typeof AuthenticatedDashboardMensagensRouteWithChildren
  AuthenticatedDashboardPerfilRoute: typeof AuthenticatedDashboardPerfilRoute
  AuthenticatedDashboardSaudeRoute: typeof AuthenticatedDashboardSaudeRouteWithChildren
  AuthenticatedDashboardSolicitacoesRoute: typeof AuthenticatedDashboardSolicitacoesRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminUsuariosRoute: typeof AuthenticatedDashboardAdminUsuariosRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdotadosRoute: AuthenticatedDashboardAdotadosRoute,
    AuthenticatedDashboardAnimaisRoute:
      AuthenticatedDashboardAnimaisRouteWithChildren,
    AuthenticatedDashboardDocumentosRoute:
      AuthenticatedDashboardDocumentosRouteWithChildren,
    AuthenticatedDashboardMensagensRoute:
      AuthenticatedDashboardMensagensRouteWithChildren,
    AuthenticatedDashboardPerfilRoute: AuthenticatedDashboardPerfilRoute,
    AuthenticatedDashboardSaudeRoute:
      AuthenticatedDashboardSaudeRouteWithChildren,
    AuthenticatedDashboardSolicitacoesRoute:
      AuthenticatedDashboardSolicitacoesRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminUsuariosRoute:
      AuthenticatedDashboardAdminUsuariosRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedMensagensRouteChildren {
  AuthenticatedMensagensConversaIdRoute: typeof AuthenticatedMensagensConversaIdRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
}

const AuthenticatedMensagensRouteChildren: AuthenticatedMensagensRouteChildren =
  {
    AuthenticatedMensagensConversaIdRoute:
      AuthenticatedMensagensConversaIdRoute,
    AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  }

const AuthenticatedMensagensRouteWithChildren =
  AuthenticatedMensagensRoute._addFileChildren(
    AuthenticatedMensagensRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedFeelsRoute: typeof AuthenticatedFeelsRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRouteWithChildren
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedMeusFavoritosRoute: typeof AuthenticatedMeusFavoritosRoute
  AuthenticatedMinhasSolicitacoesRoute: typeof AuthenticatedMinhasSolicitacoesRoute
  AuthenticatedTriagemRoute: typeof AuthenticatedTriagemRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedFeelsRoute: AuthenticatedFeelsRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRouteWithChildren,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedMeusFavoritosRoute: AuthenticatedMeusFavoritosRoute,
  AuthenticatedMinhasSolicitacoesRoute: AuthenticatedMinhasSolicitacoesRoute,
  AuthenticatedTriagemRoute: AuthenticatedTriagemRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CadastroRouteChildren {
  CadastroAcolhedorRoute: typeof CadastroAcolhedorRoute
  CadastroAdotanteRoute: typeof CadastroAdotanteRoute
  CadastroOrganizacaoRoute: typeof CadastroOrganizacaoRoute
  CadastroIndexRoute: typeof CadastroIndexRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroAcolhedorRoute: CadastroAcolhedorRoute,
  CadastroAdotanteRoute: CadastroAdotanteRoute,
  CadastroOrganizacaoRoute: CadastroOrganizacaoRoute,
  CadastroIndexRoute: CadastroIndexRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CadastroRoute: CadastroRouteWithChildren,
  LoginRoute: LoginRoute,
  VitrineRoute: VitrineRoute,
  AdotantesAdotanteIdRoute: AdotantesAdotanteIdRoute,
  AnimaisAnimalIdRoute: AnimaisAnimalIdRoute,
  OrganizacoesOrganizacaoIdRoute: OrganizacoesOrganizacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
